### PR TITLE
Fix the exception log issue

### PR DESCRIPTION
**Pull request by aldbr**
Here is a fix for the exception log issue. #22 
I created one formatter based on the logging formatter which initializes exc_text containing the exception stacktrace and I replace the exception type by its string representation in exc_info. 

I tested it, it seems totally fine.

### CODE REVIEW

**Comment by aldbr** [comment]
This was the last adjustment, you can merge it if it is good for you.  
Thank you in advance

**Comment by aldbr** [comment]
This was the last adjustment, you can merge it if it is good for you.
Thank you in advance

**Comment by cmanaha** [comment]
Will take a look over the weekend and release if everything goes well

Saludos - Cheers
Carlos

**Comment by chaen** [comment]
This would indeed be a very useful fix !  :+1:

**Pull request merged**
