### PR TITLE
Adding aws eleasticsearch authentication

### PR DESCRIPTION
**Pull request by KonstantinSchubert**
Feel free to request changes or edit my pull request before merging.

### CODE REVIEW

**Comment by cmanaha** [comment]
Looks pretty straightforward to me; Thanks a lot for the pull-request and contribution
Some tests are not passing (Definition list ends without a blank line; unexpected unindent upon tox execution) I'll  take a look, test it and merge it. If everything goes well I'll also force a package release as there might be others interested on this!

**Comment by KonstantinSchubert** [comment]
Should I fix the formatting problems or are you taking care of this?

**Comment by cmanaha** [comment]
Go for it

Otherwise I'll pick it up as soon I have some spare time

Carlos

**Comment by KonstantinSchubert** [comment]
Frankly I am not sure what the right format is for these comments, so it would take me a long time to figure this out. I think for you it is just a minute or two.

**Comment by cmanaha** [comment]
That's fine. I'll take care of it as soon as I have some spare time.

**Comment by KonstantinSchubert** [comment]
@cmanaha It looks liek I have to add some tests?

**Comment by cmanaha** [comment]
@KonstantinSchubert on the testing issues; Pretty much passes coverage and what is missing is integration tests for authentication of all kinds; This are difficult to test on free continuous integration systems (except may be the basic auth on top of ES) specially as they require a Kerberos setup and IAM details to consider.  If you have any thoughts on how they will be welcome. Otherwise only option is to test the integration manually; By the way, I released your changes on to pypi https://pypi.python.org/pypi/CMRESHandler/1.0.0b3

**Comment by KonstantinSchubert** [comment]
:+1:

**Pull request merged**
